// TODO autogenerated leave only essential fields and add validation
type WeatherInfo = {
  coord: { lon: number; lat: number };
  dt: number;
  id: number;
  main: { temp: number; feels_like: number; temp_min: number; temp_max: number; pressure: number; sea_level: number; grnd_level: number; humidity: number };
  name: string;
  sys: { country: string; timezone: number; sunrise: number; sunset: number };
  visibility: number;
  weather: { id: number; main: string; description: string; icon: string }[];
  wind: { speed: number; deg: number };
  clouds: { all: number };
};

export default WeatherInfo;